version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
